name: update
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Septang1e/waka-box@master
        env:
          GIST_ID:  df2f69c640ec3b02f0336a742b199563
          GH_TOKEN:  ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY:  ${{ secrets.WAKATIME_API_KEY }}
