name: update
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Septang1e/waka-box@master
        env:
          GIST_ID:  0fa52bc18220f0bacd22cf30fbaf777d
          GH_TOKEN:  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
          WAKATIME_API_KEY:  waka_f82e5907-5335-45c2-9205-5ef5decdcafe
