name: update
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    name: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Septang1e/waka-box@master
        env:
          GIST_ID:  802604ea5cf28fbfad61a7316a446c6e
          GH_TOKEN:  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
          WAKATIME_API_KEY:  ${{ secrets.WAKATIME_API_KEY }}
